trigger:
 branches:
  include:
    - main
 paths:
   exclude:
     - ado

name: Deploy Core Bicep files - $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)-$(Hours)$(Minutes)$(Seconds)   

variables:
  vmImageName: 'ubuntu-latest'
  devAzureServiceConnection: 'russ-airs'
  testAzureServiceConnection: 'russ-airs'
  prodAzureServiceConnection: 'russ-airs'
  location: 'uksouth'
  resourceGroupName: 'rg-office365-demo'
  logicAppName: 'logicapp-office365-dev'

stages:
- stage: 'dev_deploy'
  displayName: 'Deploy to Dev Environment Stage'
  jobs:
  - deployment: 'dev_deploy_bicep'
    displayName: 'Deploy to Dev Environment Deployment'
    pool:
      vmImage: $(vmImageName)
    environment: 
      name: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: 'Azure CLI Deploy Function App'
            inputs:
              azureSubscription: $(devAzureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                cd Bicep
                az deployment group create --name fnappdeploy -g $(resourceGroupName) --template-file fnapp.bicep

          - task: AzureCLI@2
            displayName: 'Azure CLI Rename logic apps params files'
            inputs:
              azureSubscription: $(devAzureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                mv ./parameters.json ./parameters.local.json
                mv ./parameters.portal.json ./parameters.json

          - task: CopyFiles@2
            displayName: 'Copy Logic App Files to logic-app'
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: |
                host.json
                connections.json
                Artifacts/**/*
                Office365/**
                parameters.json
              TargetFolder: 'logic-app'

          - task: ArchiveFiles@2
            displayName: 'Create workflows ZIP'
            inputs: 
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/logic-app'
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/logic-app/$(Build.BuildId).zip'
              replaceExistingArchive: true

          - task: AzureFunctionApp@1
            displayName: 'Deploy workflows to Function App'
            inputs:
              azureSubscription: $(devAzureServiceConnection)
              appName: '$(logicAppName)'
              appType: 'workflowapp'
              package: '$(Build.ArtifactStagingDirectory)/logic-app/$(Build.BuildId).zip'
              deploymentMethod: 'zipDeploy'                 